### ISSUE TITLE
Error code 429

### ISSUE THREAD

**Issue by MeanSquaredError** [MTProto-Devs/RPC-errors#2]
The list lacks error code 429 "Too many requests: retry later", which seems to be some kind of rate limit code.
Sometimes the message is formatted like this "Too Many Requests: retry after 333"

From this page:
https://core.telegram.org/bots/faq

> My bot is hitting limits, how do I avoid this?
>
> When sending messages inside a particular chat, avoid sending more than one message per second. We may allow short bursts that go over this limit, but eventually you'll begin receiving 429 errors.

**Comment by Lonami** [comment]
This repository has not been maintained in years. Perhaps it should be archived.

**Comment by Lonami** [comment]
Closing due to https://github.com/MTProto-Devs/RPC-errors/commit/d798e7aa58ae1096a87af303ca72b0a6e6a4b0b1.
